=== LeBaThuan/ans-schema/src/main/resources/schema/ans/v0_2/content.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/v0_2/content.json",
    "title": "ANS Content root level schema",
    "description": "Content FIXME FILL ME IN.",
    "type": "object",
    "required": ["id", "created_date"],
    "additionalProperties": false,
    "properties": {
        "id": {
            "description": "A globally unique identifier of the content in the ANS repository.",
            "type": "string"
        },
        "created_date": {
            "description": "When the content was originally created (RFC3339-formatted).",
            "type": "string",
            "format": "date-time"
        },
        "last_updated_date": {
            "description": "When the content was last updated (RFC3339-formatted).",
            "type": "string",
            "format": "date-time"
        },
        "credit": {
            "description": "An array of people/groups attributed to this content.",
            "type": "array",
            "items": {
                "$ref": "credit.json"
            }
        }
    }
}

=== LeBaThuan/ans-schema/src/test/resources/com/washingtonpost/arc/ans/v0_2/model/content-fixture-good.json
{
    "id": "some globally unique ANS id",
    "created_date": "2015-06-25T09:50:50.52Z",
    "last_updated_date": "2015-06-25T09:51:50.52Z",
    "credit": [
        {
            "name": "The Dude Getting Credit",
            "org": "The Washington Post",
            "role": "Author"
        },
        {
            "name": "Someone Else",
            "org": "The Washington Times",
            "role": "Contributor"
        }
    ]
}
